### ISSUE TITLE
Documentation is Lacking for things missing in Config Example

### ISSUE THREAD

**Issue by oneproxima** [flo-at/minmon#109]
As a user that understands the basics of TOML I don't understand the expectations for the format of the TOML for it to be right.

e.i. in the example config everything is `[[x]]` but when I go and do `[[log]]` I get and error and after making a discussion and only realizing it should be `[log]`.

Another example:

`
[report]
interval = 6
events = ["Event 1"]

[event]
name = "Event 1"
action = "Webhook 1a"

[[actions]]
name = "Webhook 1a"
type = "Webhook"
url = "https://discord.com/api/webhooks/"
body = """{"username": "Webhook", "avatar_url": "https://i.imgur.com/4M34hi2.png", "content": "Report"}"""
headers = {"Content-Type" = "application/json"}
`

I get the error:

`
[+] Running 1/0
 ✔ Container minmon-minmon-1  Created                                                                                                                     0.0s 
Attaching to minmon-minmon-1
minmon-minmon-1  | Exiting due to error: Failed to parse config file: TOML parse error at line 36, column 11
minmon-minmon-1  |    |
minmon-minmon-1  | 36 | events = ["Event 1"]
minmon-minmon-1  |    |           ^^^^^^^^^
minmon-minmon-1  | invalid type: string "Event 1", expected struct ReportEvent
minmon-minmon-1  | 
minmon-minmon-1  | 
minmon-minmon-1 exited with code 1
`

I don't know how to format ReportEvent and trying to base it off of the examples doesn't show me enough to get a working example. More information would be appreciated.

**Comment by flo-at** [comment]
Hi there,
the TOML syntax can be a bit confusing sometimes. Especially because sometimes there is more than one way to do the same thing.

In TOML vocabulary, "report->events" is a [nested array of tables](https://toml.io/en/v1.0.0#array-of-tables) which is part of the report [table](https://toml.io/en/v1.0.0#table).
That means, you can set the options like this:
```toml
[report] # this table is optional; if the defaults are okay for you, you can skip this
interval = 500

[[report.events]]
name = "First Report"
action = "Email action 1"

[[report.events]]
name = "Second Report"
action = "Email action 2"

# ...
```

The double brackets mean that it's an array, so there may be more than one event for the report. The report is just a regular table (not an array or something) so there's just one pair of brackets.

Does that fix your problem?

For the documentation, I'll think about how to improve this. Maybe it just needs more examples because I don't want to repeat the TOML documentation here and examples are a good way to get started quickly.

Cheers!

**Comment by oneproxima** [comment]
I'll give this a try! But I think examples are the way to go, thanks for the quick response

**Comment by oneproxima** [comment]
Edit: this worked! I really appreciate it. A thought is to have an example that would create a report at least once a day or something so to test/see that it's working.
